### ISSUE TITLE
MRV heuristic should choose smallest domain

### ISSUE THREAD

**Issue by cassdeckard** [davecom/SwiftCSP#1]
The currently implemented MRV heuristic appears to be choosing a variable with the largest domain. But unless I'm misunderstanding something, MRV should choose the _smallest_ domain instead, right?

MRV stands for "minimum remaining values" - it even says so in the code in a comment on line 87:

```
/// Return an unassigned variable - we may want to use some logic here to return the
/// minimum-remaining values
```

But then later the variable name is `maximumRemainingValues` and the code follows that logic

**Comment by davecom** [comment]
Hi @mattdeckard , you're right! I have fixed this in the latest commit on the swift3 branch.
