### ISSUE TITLE
Add Testing Support on Linux

### ISSUE THREAD

**Issue by davecom** [davecom/SwiftCSP#7]

**Comment by felix91gr** [comment]
+1, your project looks really cool :)

I can run the tests and maybe fix them if you need any help. I work on Linux ^^

**Comment by davecom** [comment]
@felix91gr Thanks for the push. Linux testing is now supported.

**Comment by felix91gr** [comment]
Not a problem! I mean, I love CSPs. I managed to get my hands on Rina Dechter's book and it's sooo great <3

I hope someday I can play with your library a bit and implement a couple of heuristics 😊. Nothing serious, but y'know, it's a thing that I like to make.

Btw, feel free to tag me if you think this is at some point production-ready. There aren't many solvers written in Swift, and I'd gladly add it to the index if the design allows it to be used in a more general context ^^ (you can also submit a PR whenever you want)
